#!/usr/bin/env node
// Scenario suite for plugins/major-tom/migration.js, the artifact map (D54).
//
// Run with: node tests/migration.test.js
//
// Node built-ins only: node:test and node:assert/strict, no runner to install, no
// dependencies. The suite is written against the specification (D54 and the module's own
// header, which states the four modes and what each one promises), never against the
// implementation: the four modes are driven as a real child process over a real directory
// tree, which is the only way to observe the one promise that matters most, that --plan
// writes nothing.
//
// Every fixture is a throwaway directory under os.tmpdir(), built by onboardedProject and
// removed by the test that built it. Nothing is ever written inside this repository. The
// fixtures are not git repositories: the map reads the filesystem and the config and never
// asks git anything, so initialising one would only claim a dependency that does not exist.
//
// The --check failure cases need a plugin root that is wrong, and the plugin root is
// resolved from the script's own __dirname, so those tests copy the whole plugin directory
// into os.tmpdir() and damage the copy. That is the only way to make the gate fail without
// damaging this repository, which is exactly what the gate exists to prevent.

'use strict'

const test = require('node:test')
const assert = require('node:assert/strict')
const { spawnSync } = require('node:child_process')
const crypto = require('node:crypto')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')

const REPO_ROOT = path.resolve(__dirname, '..')
const PLUGIN_ROOT = path.join(REPO_ROOT, 'plugins', 'major-tom')
const SCRIPT = path.join(PLUGIN_ROOT, 'migration.js')

// The persistence root every fixture uses; the config schema fixes it to .knowledge.
const KNOWLEDGE_ROOT = '.knowledge'
const AREAS = ['memories', 'docs', 'runs', 'monitors', 'logs']

// The markers and managed values the map declares, written here literally rather than
// imported: the suite tests the specification, so a disagreement between these and the
// module is exactly what these tests exist to report.
const HTML_BEGIN = '<!-- major-tom:begin -->'
const HTML_END = '<!-- major-tom:end -->'
const GITIGNORE_BEGIN = '# major-tom:begin'
const GITIGNORE_END = '# major-tom:end'
const IGNORED_PATHS = ['.claude/worktrees/', '.claude/session/', '.claude/server/']
const LAUNCH_ENTRY_NAME = 'major-tom-dashboard'
const LAUNCHER_PROGRAM = '.claude/server/launcher.js'

// The plugin versions the transitions turn on, as D54 records them. CURRENT is the version the
// newest transition ships in, so a fixture stamped with it is a project onboarded by the plugin
// as it stands.
const BEFORE_EVERYTHING = '0.19.0'
const CURRENT = '0.29.0'

// The suffix D55 quarantines onto.
const RETIRED_SUFFIX = '.retired'

// ---------------------------------------------------------------------------
// The two retired artifacts, in the bytes they actually had.
//
// These are not imitations. D55 lets one mode of the map move a file in somebody's
// repository, and the only thing standing between that mode and a stranger's file is the
// evidence, so a fixture invented here would prove nothing except that the map matches
// whatever this file made up. Both constants are lifted verbatim from the commits that
// retired the artifacts, by line range, and both ranges are recorded so anyone can re-derive
// and diff them:
//
//   git show 88edb9a^:plugins/major-tom/templates/dashboard.html \
//     | sed -n '1,8p;82,88p;844,845p'
//   git show a8a6b1f^:plugins/major-tom/templates/dashboard-server.js \
//     | sed -n '1,13p;82,85p'
//
// The excerpts drop the middle of each file, which is 46 KB of CSS and script in one case
// and the request handler in the other. Nothing dropped carries a predicate; everything kept
// is byte for byte what was there.
// ---------------------------------------------------------------------------

const RETIRED_DASHBOARD_TEMPLATE = [
  "<!doctype html>",
  "<!-- GENERATED by scripts/build-dashboard.js from templates/dashboard/. Do not edit; edit the authoring split and rebuild. -->",
  "<html lang=\"en\">",
  "<head>",
  "<meta charset=\"utf-8\">",
  "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
  "<title>Major Tom dashboard</title>",
  "<style>",
  "</style>",
  "</head>",
  "<body>",
  "",
  "<script type=\"application/json\" id=\"major-tom-data\">",
  "{}",
  "</script>",
  "</body>",
  "</html>",
].join('\n') + '\n'

const RETIRED_DASHBOARD_SERVER = [
  "#!/usr/bin/env node",
  "// Static server for the Major Tom dashboard (D31). Node, no dependencies.",
  "// Lives in the plugin (never written into the target repo); the /major-tom:dashboard",
  "// command runs it against the dashboard file in the target's persistence root.",
  "//",
  "// Usage: node dashboard-server.js <path-to-dashboard.html | directory> [port]",
  "//",
  "// Given a file: serves that single dashboard file at / (the production path).",
  "// Given a directory: serves the files inside it, path-traversal-safe (the authoring dev",
  "// loop, D34: ES modules need http, file:// blocks them). Still localhost, still GET only.",
  "// Port resolution: explicit argument, else the PORT env var (what the Claude Desktop",
  "// launch.json autoPort mechanism passes when it picks a free port, D32), else 4242.",
  "// Files are read on every request, so edits and re-injects show up on browser refresh.",
  "",
  "server.listen(port, '127.0.0.1', () => {",
  "  console.log(`major-tom dashboard on http://localhost:${port} (serving ${target})`)",
  "})",
].join('\n') + '\n'

// The template above is what the plugin shipped; what landed in a target repository was that
// template with the data island filled in, because `render.js inject` replaced the island
// content and left every other byte alone. The regex is the one the retired inject used, so
// the fixture is produced the way the artifact was produced rather than typed out as
// somebody's idea of the result.
function injectIsland(html, data) {
  const island = /(<script[^>]*id="major-tom-data"[^>]*>)[\s\S]*?(<\/script>)/
  assert.ok(island.test(html), 'the historic template must carry the island inject anchored on')
  return html.replace(island, '$1\n' + JSON.stringify(data) + '\n$2')
}

// What an onboard of that era actually wrote into <persistence.root>/dashboard.html.
function retiredDashboardArtifact() {
  return injectIsland(RETIRED_DASHBOARD_TEMPLATE, { project: { name: 'fixture' }, generatedAt: '2026-08-06T10:00:00Z' })
}

// ---------------------------------------------------------------------------
// Fixture builders
// ---------------------------------------------------------------------------

function tempDir(prefix) {
  return fs.mkdtempSync(path.join(os.tmpdir(), prefix))
}

function write(root, relative, content) {
  const full = path.join(root, relative)
  fs.mkdirSync(path.dirname(full), { recursive: true })
  fs.writeFileSync(full, content)
  return full
}

function defaultConfig(overrides) {
  const config = {
    schemaVersion: 1,
    onboard: { completedAt: '2026-08-07T10:00:00Z', pluginVersion: CURRENT },
    project: { name: 'fixture', description: '', type: 'existing', topology: 'single' },
    execution: { workingModel: 'subagents' },
    persistence: { root: KNOWLEDGE_ROOT },
    snapshot: { days: 30, limit: 500 },
    stack: { languages: [], frameworks: [], databases: [], messaging: [] },
    devops: { ci: '', containers: '', cloud: '' },
    org: { namespace: '@fixture', internalLibraries: [], preferredLibraries: [] },
    sources: { issueTracker: { provider: '', project: '' }, sites: [] },
    mcp: ['codebase-memory-mcp'],
    specialists: [],
  }
  return Object.assign(config, overrides || {})
}

const RUN_RECORD_NAME = 'onboard-2026-08-07T10-00-00-000Z.md'

// The onboard run record, in the two shapes a repository can hold it. Both are the same
// artifact at the same path: type run, the same title, the same generated block, the same prose
// body. The run block of D57 is the only difference, written the way the Finalize prompt asks
// for it, a nested block with one entry per phase and stamps only where a phase has them.
function runRecord(options) {
  const opts = options || {}
  const name = opts.name || RUN_RECORD_NAME
  const head = [
    '---',
    'type: run',
    'title: Onboard',
    'generated: {by: major-tom-onboard, at: 2026-08-07T10:00:00Z}',
  ]
  const block = [
    'run:',
    '  id: ' + name.replace(/\.md$/, ''),
    '  workflow: onboard',
    '  mode: subagents',
    '  startedAt: 2026-08-07T09:58:00Z',
    '  finishedAt: 2026-08-07T10:00:00Z',
    '  phases:',
    '    - name: Check',
    '      status: done',
    '    - name: Execute',
    '      artifact: .claude/major-tom.json',
    '      status: done',
    '      startedAt: 2026-08-07T09:58:00Z',
    '      finishedAt: 2026-08-07T09:59:30Z',
    '    - name: Finalize',
    '      artifact: ' + KNOWLEDGE_ROOT + '/runs/' + name,
    '      status: active',
    '      startedAt: 2026-08-07T10:00:00Z',
  ]
  return head
    .concat(opts.runBlock ? block : [], ['---', '', 'Onboard run record.', ''])
    .join('\n')
}

// A project in the shape a current onboard leaves behind: every entry the map declares as
// always required, and nothing else. `runBlock: false` writes the run record as a plugin before
// D57 wrote it, which is the same artifact minus that block.
function onboardedProject(options) {
  const opts = options || {}
  const root = tempDir('major-tom-map-')
  const config = defaultConfig(opts.config)

  write(root, '.claude/major-tom.json', JSON.stringify(config, null, 2) + '\n')

  for (const area of AREAS) {
    fs.mkdirSync(path.join(root, KNOWLEDGE_ROOT, area), { recursive: true })
    write(root, KNOWLEDGE_ROOT + '/' + area + '/.gitkeep', '')
  }
  write(
    root,
    KNOWLEDGE_ROOT + '/index.md',
    ['---', 'okf_version: 0.2', '---', '', '## runs', '', '- runs/onboard-fixture.md type=run', ''].join('\n')
  )
  write(root, KNOWLEDGE_ROOT + '/runs/' + RUN_RECORD_NAME, runRecord({ runBlock: opts.runBlock !== false }))

  write(root, 'AGENTS.md', [HTML_BEGIN, '# fixture', '', 'Context.', HTML_END, ''].join('\n'))
  write(root, 'CLAUDE.md', [HTML_BEGIN, '@AGENTS.md', HTML_END, ''].join('\n'))

  fs.mkdirSync(path.join(root, '.claude', 'server'), { recursive: true })
  fs.copyFileSync(path.join(PLUGIN_ROOT, 'app', 'launcher.js'), path.join(root, '.claude', 'server', 'launcher.js'))

  write(
    root,
    '.claude/launch.json',
    JSON.stringify(
      {
        version: '0.0.1',
        configurations: [
          Object.assign(
            { name: LAUNCH_ENTRY_NAME, program: LAUNCHER_PROGRAM, args: [], port: 4242, autoPort: true },
            opts.launchEntry || {}
          ),
        ],
      },
      null,
      2
    ) + '\n'
  )

  write(
    root,
    '.claude/settings.json',
    JSON.stringify(
      {
        env: { CLAUDE_CODE_SUBPROCESS_ENV_SCRUB: '1', CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS: '1' },
        alwaysThinkingEnabled: true,
      },
      null,
      2
    ) + '\n'
  )

  write(
    root,
    '.gitignore',
    ['node_modules/', '', GITIGNORE_BEGIN, '# Major Tom mechanism state, never knowledge.'].concat(IGNORED_PATHS, [GITIGNORE_END, '']).join('\n')
  )

  for (const specialist of config.specialists) {
    write(
      root,
      '.claude/agents/' + specialist.name + '.md',
      [
        '---',
        'name: ' + specialist.name,
        'description: A fixture specialist.',
        'tools: ' + (opts.specialistTools === undefined ? derivedTools(config) : opts.specialistTools),
        '---',
        '',
        'Body.',
        '',
      ].join('\n')
    )
  }

  return root
}

function derivedTools(config) {
  return ['Read', 'Glob', 'Grep'].concat((config.mcp || []).map((s) => 'mcp__' + s + '__*')).join(', ')
}

function remove(root) {
  fs.rmSync(root, { recursive: true, force: true })
}

// ---------------------------------------------------------------------------
// Running the script
// ---------------------------------------------------------------------------

function run(args, options) {
  const opts = options || {}
  const result = spawnSync(process.execPath, [opts.script || SCRIPT].concat(args), {
    encoding: 'utf8',
    cwd: opts.cwd || REPO_ROOT,
  })
  return { status: result.status, stdout: result.stdout || '', stderr: result.stderr || '', all: (result.stdout || '') + (result.stderr || '') }
}

// The status lines the map prints are the contract this suite reads, so they are matched
// on the status token and the path together rather than on a substring of the whole output.
function lineFor(output, status, target) {
  return output
    .split('\n')
    .filter((line) => line.startsWith(status + ' ') && line.indexOf(target) !== -1)
}

function statusOf(output, target) {
  for (const line of output.split('\n')) {
    const match = /^(\S+)\s+(\S+)\s/.exec(line)
    if (match && match[2] === target) return match[1]
  }
  return null
}

// A content hash of a whole directory tree, path by path, so a test can assert that a mode
// changed nothing at all rather than that it changed nothing it happened to look at.
function treeDigest(root) {
  const hash = crypto.createHash('sha256')
  const walk = (dir, prefix) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => (a.name < b.name ? -1 : 1))) {
      const full = path.join(dir, entry.name)
      const rel = prefix ? prefix + '/' + entry.name : entry.name
      if (entry.isDirectory()) {
        hash.update('D ' + rel + '\n')
        walk(full, rel)
      } else {
        hash.update('F ' + rel + ' ' + crypto.createHash('sha256').update(fs.readFileSync(full)).digest('hex') + '\n')
      }
    }
  }
  walk(root, '')
  return hash.digest('hex')
}

// ---------------------------------------------------------------------------
// --verify
// ---------------------------------------------------------------------------

test('--verify accepts a correctly onboarded project', (t) => {
  const repo = onboardedProject()
  t.after(() => remove(repo))

  const result = run(['--verify', repo])
  assert.equal(result.status, 0, result.all)
  assert.match(result.stdout, /verify: \d+ ok, \d+ absent, 0 missing, 0 unrecognised, 0 unexpected, 0 retired/)
})

test('--verify reports every always-required artifact it declares', (t) => {
  const repo = onboardedProject()
  t.after(() => remove(repo))

  const result = run(['--verify', repo])
  for (const target of [
    '.claude/major-tom.json',
    KNOWLEDGE_ROOT,
    KNOWLEDGE_ROOT + '/memories',
    KNOWLEDGE_ROOT + '/index.md',
    'AGENTS.md',
    'CLAUDE.md',
    '.claude/launch.json',
    '.claude/settings.json',
    '.gitignore',
    '.claude/server/launcher.js',
  ]) {
    assert.equal(statusOf(result.stdout, target), 'ok', 'expected ok for ' + target + '\n' + result.all)
  }
})

test('--verify refuses a directory that is not an onboarded project', (t) => {
  const repo = tempDir('major-tom-map-bare-')
  t.after(() => remove(repo))

  const result = run(['--verify', repo])
  assert.equal(result.status, 1)
  assert.match(result.stderr, /not an onboarded project/)
})

test('--verify reports what is missing, one line per artifact', (t) => {
  const repo = onboardedProject()
  t.after(() => remove(repo))

  fs.rmSync(path.join(repo, 'AGENTS.md'))
  fs.rmSync(path.join(repo, KNOWLEDGE_ROOT, 'monitors'), { recursive: true })
  fs.rmSync(path.join(repo, '.claude', 'server', 'launcher.js'))

  const result = run(['--verify', repo])
  assert.equal(result.status, 1)
  assert.equal(statusOf(result.stdout, 'AGENTS.md'), 'MISSING', result.all)
  assert.equal(statusOf(result.stdout, KNOWLEDGE_ROOT + '/monitors'), 'MISSING', result.all)
  assert.equal(statusOf(result.stdout, '.claude/server/launcher.js'), 'MISSING', result.all)
  assert.match(result.stdout, /3 missing/)
})

test('--verify tells an absent artifact apart from one present but not recognisably ours', (t) => {
  const absentRepo = onboardedProject()
  const strangerRepo = onboardedProject()
  t.after(() => {
    remove(absentRepo)
    remove(strangerRepo)
  })

  fs.rmSync(path.join(absentRepo, '.claude', 'server', 'launcher.js'))
  // Same path, a file that is not the launcher this plugin ships. Byte-identical evidence
  // is the only thing that can tell these two situations apart, and they migrate
  // differently: one is restored by a re-onboard, the other is somebody else's file.
  fs.writeFileSync(path.join(strangerRepo, '.claude', 'server', 'launcher.js'), '// not ours\n')

  const absent = run(['--verify', absentRepo])
  const stranger = run(['--verify', strangerRepo])

  assert.equal(statusOf(absent.stdout, '.claude/server/launcher.js'), 'MISSING', absent.all)
  assert.equal(statusOf(stranger.stdout, '.claude/server/launcher.js'), 'UNRECOGNISED', stranger.all)
  assert.match(stranger.stdout, /differs from the plugin's app\/launcher\.js/)
  assert.equal(absent.status, 1)
  assert.equal(stranger.status, 1)
})

test('--verify calls a managed block without its markers unrecognised, not missing', (t) => {
  const repo = onboardedProject()
  t.after(() => remove(repo))

  fs.writeFileSync(path.join(repo, 'AGENTS.md'), '# fixture\n\nNo markers here.\n')

  const result = run(['--verify', repo])
  assert.equal(statusOf(result.stdout, 'AGENTS.md'), 'UNRECOGNISED', result.all)
  assert.match(result.stdout, /marker pair/)
})

test('--verify checks the gitignore block content, not only its markers', (t) => {
  const repo = onboardedProject()
  t.after(() => remove(repo))

  write(repo, '.gitignore', [GITIGNORE_BEGIN, '.claude/session/', GITIGNORE_END, ''].join('\n'))

  const result = run(['--verify', repo])
  assert.equal(statusOf(result.stdout, '.gitignore'), 'UNRECOGNISED', result.all)
  assert.match(result.stdout, /\.claude\/worktrees\//)
})

test('--verify checks each managed settings key', (t) => {
  const repo = onboardedProject()
  t.after(() => remove(repo))

  write(repo, '.claude/settings.json', JSON.stringify({ env: { CLAUDE_CODE_SUBPROCESS_ENV_SCRUB: '1' } }, null, 2))

  const result = run(['--verify', repo])
  assert.equal(statusOf(result.stdout, '.claude/settings.json'), 'UNRECOGNISED', result.all)
  assert.match(result.stdout, /alwaysThinkingEnabled/)
})

test('--verify follows the settings file choice: settings.local.json wins when it exists', (t) => {
  const repo = onboardedProject()
  t.after(() => remove(repo))

  write(
    repo,
    '.claude/settings.local.json',
    JSON.stringify({ env: { CLAUDE_CODE_SUBPROCESS_ENV_SCRUB: '1', CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS: '1' }, alwaysThinkingEnabled: true })
  )

  const result = run(['--verify', repo])
  assert.equal(statusOf(result.stdout, '.claude/settings.local.json'), 'ok', result.all)
  assert.equal(statusOf(result.stdout, '.claude/settings.json'), null, 'the shared file must not be reported once the local one exists')
})

test('--verify reports a stranger file in a directory the plugin owns whole', (t) => {
  const repo = onboardedProject()
  t.after(() => remove(repo))

  write(repo, '.claude/server/leftover.js', '// something else\n')

  const result = run(['--verify', repo])
  assert.equal(result.status, 1)
  assert.equal(lineFor(result.stdout, 'UNEXPECTED', '.claude/server/leftover.js').length, 1, result.all)
  assert.match(result.stdout, /1 unexpected/)
})

test('--verify leaves a knowledge area alone: the user writes there and the plugin does not own it', (t) => {
  const repo = onboardedProject()
  t.after(() => remove(repo))

  write(repo, KNOWLEDGE_ROOT + '/memories/a-fact.md', '---\ntype: memory\n---\n\nA fact.\n')

  const result = run(['--verify', repo])
  assert.equal(result.status, 0, result.all)
  assert.equal(result.stdout.indexOf('a-fact.md'), -1, 'a user knowledge file must never be reported')
})

test('--verify counts a project with no specialists as complete', (t) => {
  const repo = onboardedProject()
  t.after(() => remove(repo))

  const result = run(['--verify', repo])
  assert.equal(result.status, 0, result.all)
  assert.match(result.stdout, /absent\s+\.claude\/agents\/<specialist\.name>\.md.*lists no specialists/)
})

test('--verify expands one entry per configured specialist', (t) => {
  const repo = onboardedProject({
    config: { specialists: [{ name: 'typescript-pro', source: 'sub-agents.directory' }] },
  })
  t.after(() => remove(repo))

  const ok = run(['--verify', repo])
  assert.equal(statusOf(ok.stdout, '.claude/agents/typescript-pro.md'), 'ok', ok.all)
  assert.equal(ok.status, 0, ok.all)

  fs.rmSync(path.join(repo, '.claude', 'agents', 'typescript-pro.md'))
  const missing = run(['--verify', repo])
  assert.equal(statusOf(missing.stdout, '.claude/agents/typescript-pro.md'), 'MISSING', missing.all)
  assert.equal(missing.status, 1)
})

test('--verify accepts an onboard run record with or without the run block', (t) => {
  // The regression this suite exists to catch on the D57 side. The block is not evidence: a
  // record written before it is just as much ours, and calling it UNRECOGNISED would report
  // true history as a defect and offer no way out, because a run record is never rewritten.
  const current = onboardedProject()
  const older = onboardedProject({ runBlock: false, config: { onboard: { completedAt: '2026-08-06T10:00:00Z', pluginVersion: BEFORE_EVERYTHING } } })
  t.after(() => {
    remove(current)
    remove(older)
  })

  const record = KNOWLEDGE_ROOT + '/runs/' + RUN_RECORD_NAME
  for (const [label, repo] of [['with the block', current], ['without it', older]]) {
    const result = run(['--verify', repo])
    assert.equal(statusOf(result.stdout, record), 'ok', 'the record ' + label + ' must verify\n' + result.all)
    assert.equal(result.status, 0, result.all)
  }
})

test('--verify reports a retired artifact wherever it finds one, whatever the config says', (t) => {
  const repo = onboardedProject()
  t.after(() => remove(repo))

  // The config claims the current version, so no version comparison would look here.
  write(repo, KNOWLEDGE_ROOT + '/dashboard.html', '<!doctype html>\n')

  const result = run(['--verify', repo])
  assert.equal(result.status, 1)
  assert.equal(lineFor(result.stdout, 'RETIRED', KNOWLEDGE_ROOT + '/dashboard.html').length, 1, result.all)
})

test('--verify reports a quarantined residue and does not call it a problem', (t) => {
  const repo = onboardedProject()
  t.after(() => remove(repo))

  write(repo, KNOWLEDGE_ROOT + '/dashboard.html' + RETIRED_SUFFIX, retiredDashboardArtifact())

  const result = run(['--verify', repo])
  assert.equal(result.status, 0, result.all)
  assert.equal(lineFor(result.stdout, 'quarantined', KNOWLEDGE_ROOT + '/dashboard.html' + RETIRED_SUFFIX).length, 1, result.all)
  assert.match(result.stdout, /0 retired, 1 quarantined/)
})

test('--verify never calls a quarantined residue unexpected inside a directory the plugin owns whole', (t) => {
  // .claude/server/ is ownsContents, so without this the remedy would install a permanent
  // new problem: quarantine the aged server copy and --verify would report the result as a
  // stranger file on every run from then on.
  const repo = onboardedProject()
  t.after(() => remove(repo))

  write(repo, '.claude/server/dashboard-server.js' + RETIRED_SUFFIX, RETIRED_DASHBOARD_SERVER)

  const result = run(['--verify', repo])
  assert.equal(result.status, 0, result.all)
  assert.equal(lineFor(result.stdout, 'UNEXPECTED', 'dashboard-server.js').length, 0, result.all)
  assert.equal(lineFor(result.stdout, 'quarantined', '.claude/server/dashboard-server.js' + RETIRED_SUFFIX).length, 1, result.all)
  assert.match(result.stdout, /0 unexpected, 0 retired, 1 quarantined/)
})

test('--verify still calls residue that is present RETIRED, quarantined copy beside it or not', (t) => {
  // The state a repository is in when --quarantine found the destination taken and refused
  // to overwrite it. Both facts are true and both are reported; the residue is still a
  // problem, because it is still there (D55 point 5).
  const repo = onboardedProject()
  t.after(() => remove(repo))

  write(repo, '.claude/server/dashboard-server.js', RETIRED_DASHBOARD_SERVER)
  write(repo, '.claude/server/dashboard-server.js' + RETIRED_SUFFIX, RETIRED_DASHBOARD_SERVER)

  const result = run(['--verify', repo])
  assert.equal(result.status, 1, 'residue still on disk is still a problem')
  assert.equal(lineFor(result.stdout, 'RETIRED', '.claude/server/dashboard-server.js').length, 1, result.all)
  assert.equal(lineFor(result.stdout, 'quarantined', '.claude/server/dashboard-server.js' + RETIRED_SUFFIX).length, 1, result.all)
  assert.match(result.stdout, /1 retired, 1 quarantined/)
})

test('--verify keeps its case contract: uppercase is a problem and quarantined is not', (t) => {
  // The rule the map states above report(): a reader and a grep both find the problems by
  // case alone. A quarantine is a state, and not a problem, so it is lowercase here. The same
  // word is uppercase in --quarantine's output because there it names an action just
  // performed, not a state observed, and this test pins both halves so neither gets "fixed"
  // into the other.
  const repo = onboardedProject()
  t.after(() => remove(repo))

  write(repo, '.claude/server/dashboard-server.js' + RETIRED_SUFFIX, RETIRED_DASHBOARD_SERVER)

  const clean = run(['--verify', repo])
  assert.equal(clean.status, 0, clean.all)
  const shouting = clean.stdout.split('\n').filter((line) => /^[A-Z]/.test(line))
  assert.deepEqual(shouting, [], 'nothing here is a problem, so nothing may be uppercase\n' + clean.all)
  assert.equal(statusOf(clean.stdout, '.claude/server/dashboard-server.js' + RETIRED_SUFFIX), 'quarantined', clean.all)

  fs.rmSync(path.join(repo, 'AGENTS.md'))
  const broken = run(['--verify', repo])
  assert.equal(broken.status, 1)
  assert.deepEqual(
    broken.stdout.split('\n').filter((line) => /^[A-Z]/.test(line)).map((line) => line.split(/\s+/)[0]),
    ['MISSING'],
    'and every uppercase line is a problem, with no exception\n' + broken.all
  )
})

test('--verify resolves the persistence root from the target config, not from a constant', (t) => {
  const repo = onboardedProject()
  t.after(() => remove(repo))

  fs.renameSync(path.join(repo, KNOWLEDGE_ROOT), path.join(repo, '.brain'))
  const config = JSON.parse(fs.readFileSync(path.join(repo, '.claude', 'major-tom.json'), 'utf8'))
  config.persistence.root = '.brain'
  write(repo, '.claude/major-tom.json', JSON.stringify(config, null, 2))

  const result = run(['--verify', repo])
  assert.equal(result.status, 0, result.all)
  assert.equal(statusOf(result.stdout, '.brain/index.md'), 'ok', result.all)
})

// ---------------------------------------------------------------------------
// --assets
// ---------------------------------------------------------------------------

test('--assets lists what the plugin actually ships, one path per line', () => {
  const result = run(['--assets'])
  assert.equal(result.status, 0, result.all)

  const lines = result.stdout.trim().split('\n')
  assert.ok(lines.length > 0)
  for (const line of lines) {
    assert.match(line, /^[A-Za-z0-9_./-]+$/, 'a consumer splits this on newlines, so a line is a path and nothing else')
    assert.ok(fs.existsSync(path.join(PLUGIN_ROOT, line)), 'listed asset does not exist in the plugin: ' + line)
  }
})

test('--assets covers every runtime asset the onboard reaches for', () => {
  const listed = run(['--assets']).stdout.trim().split('\n')
  for (const required of [
    'config.schema.json',
    'migration.js',
    'templates/context.md.tpl',
    'templates/claude.md.tpl',
    'templates/render.js',
    'templates/launch-merge.js',
    'templates/settings-merge.js',
    'templates/gitignore-merge.js',
    'app/launcher.js',
    'app/server.js',
    'app/dashboard.html',
    'app/snapshot.js',
    'app/vendor/js-yaml.cjs.js',
  ]) {
    assert.ok(listed.indexOf(required) !== -1, 'missing from --assets: ' + required)
  }
})

// ---------------------------------------------------------------------------
// writtenBy
// ---------------------------------------------------------------------------

// writtenBy is the map's only pointer from an artifact back to the mechanism that writes it,
// and for two entries that pointer names a numbered step of a prompt that lives in another
// file. No mode of the map checks it, so the two drifted once already and nothing noticed.
// This test reads the step numbers out of the onboard's own Finalize prompt and holds the map
// to them, which is the whole reason the field is worth having.
//
// The map is required here rather than driven as a child process, because writtenBy is
// documentation the modes never print.
test('writtenBy cites the Finalize steps the onboard actually numbers', () => {
  const finalize = finalizePrompt()
  const runRecordStep = stepNumber(finalize, 'Write the run record')
  const indexStep = stepNumber(finalize, "Append the run record's one-line entry")

  assert.match(
    mapEntry('run-record-onboard').writtenBy,
    new RegExp('workflows/onboard\\.js, Finalize step ' + runRecordStep + '\\b')
  )
  assert.match(
    mapEntry('bundle-index').writtenBy,
    new RegExp('appended to by Finalize step ' + indexStep + '\\b')
  )
})

// The Finalize prompt of the onboard, as source text. Its steps are numbered in the prompt
// itself, and those numbers are what writtenBy cites.
function finalizePrompt() {
  const source = fs.readFileSync(path.join(PLUGIN_ROOT, 'workflows', 'onboard.js'), 'utf8')
  const start = source.indexOf("phase('Finalize')")
  assert.notEqual(start, -1, 'the onboard must still open a Finalize phase')
  return source.slice(start)
}

function stepNumber(prompt, instruction) {
  const match = new RegExp('[`\'"](\\d+)\\. ' + instruction).exec(prompt)
  assert.ok(match, 'the Finalize prompt must still carry the step ' + JSON.stringify(instruction))
  return match[1]
}

function mapEntry(id) {
  const found = require(SCRIPT).MAP.filter((entry) => entry.id === id)
  assert.equal(found.length, 1, 'the map must declare exactly one entry with id ' + JSON.stringify(id))
  return found[0]
}

// ---------------------------------------------------------------------------
// --check
// ---------------------------------------------------------------------------

test('--check passes on this repository', () => {
  const result = run(['--check'])
  assert.equal(result.status, 0, result.all)
  assert.match(result.stdout, /artifact map consistent/)
})

test('--check fails when the map names a plugin asset that is not there', (t) => {
  const root = tempDir('major-tom-map-plugin-')
  t.after(() => remove(root))
  const copy = path.join(root, 'major-tom')
  fs.cpSync(PLUGIN_ROOT, copy, { recursive: true })
  fs.rmSync(path.join(copy, 'templates', 'render.js'))

  const result = run(['--check'], { script: path.join(copy, 'migration.js') })
  assert.equal(result.status, 1)
  assert.match(result.stderr, /required asset missing from the plugin: templates\/render\.js/)
})

test('--check fails when the map declares byte-identical evidence against a file that is gone', (t) => {
  const root = tempDir('major-tom-map-plugin-')
  t.after(() => remove(root))
  const copy = path.join(root, 'major-tom')
  fs.cpSync(PLUGIN_ROOT, copy, { recursive: true })
  fs.rmSync(path.join(copy, 'app', 'launcher.js'))

  const result = run(['--check'], { script: path.join(copy, 'migration.js') })
  assert.equal(result.status, 1)
  assert.match(result.stderr, /byte-identical evidence names a plugin file that is not there, app\/launcher\.js/)
})

test('--check fails when a mechanism stops writing what the map declares', (t) => {
  const root = tempDir('major-tom-map-plugin-')
  t.after(() => remove(root))
  const copy = path.join(root, 'major-tom')
  fs.cpSync(PLUGIN_ROOT, copy, { recursive: true })

  const merge = path.join(copy, 'templates', 'gitignore-merge.js')
  fs.writeFileSync(merge, fs.readFileSync(merge, 'utf8').split("'.claude/session/',").join(''))

  const result = run(['--check'], { script: path.join(copy, 'migration.js') })
  assert.equal(result.status, 1)
  assert.match(result.stderr, /gitignore-merge\.js no longer carries "\.claude\/session\/"/)
})

// A residue is the only thing --quarantine writes to, so declaring one without a proof of
// authorship would hand the one writing mode a path and nothing else. These two tests add
// the residue a future version might add carelessly, by injecting it into a damaged copy of
// the map at the one stable anchor the array literal has, and assert the gate refuses it
// before it can reach anybody's repository.
function pluginCopyWithTransition(t, literal) {
  const root = tempDir('major-tom-map-plugin-')
  t.after(() => remove(root))
  const copy = path.join(root, 'major-tom')
  fs.cpSync(PLUGIN_ROOT, copy, { recursive: true })

  const script = path.join(copy, 'migration.js')
  const source = fs.readFileSync(script, 'utf8')
  const anchor = 'const TRANSITIONS = ['
  assert.ok(source.indexOf(anchor) !== -1, 'the map must still declare its transitions in one array')
  fs.writeFileSync(script, source.replace(anchor, anchor + '\n  ' + literal + ','))
  return script
}

test('--check fails on a residue transition that declares no evidence', (t) => {
  const script = pluginCopyWithTransition(
    t,
    "{ id: 'unproven-residue', species: 'residue', since: '0.20.0', decision: 'none', " +
      "subject: { path: '.claude/server/whatever.js' }, describe: 'x', evidence: [], " +
      "remedy: 'quarantine', remedyBy: 'x', detect() { return [] } }"
  )

  const result = run(['--check'], { script })
  assert.equal(result.status, 1)
  assert.match(result.stderr, /unproven-residue: a residue must declare non-empty evidence/)
})

test('--check fails on a residue whose evidence is the `none` predicate', (t) => {
  // `none` is an honest declaration for a map entry that only reports. It is not one for the
  // single thing that gets moved on its evidence.
  const script = pluginCopyWithTransition(
    t,
    "{ id: 'unprovable-residue', species: 'residue', since: '0.20.0', decision: 'none', " +
      "subject: { path: '.claude/server/whatever.js' }, describe: 'x', " +
      "evidence: [{ type: 'none', why: 'nothing in it says it is ours' }], " +
      "remedy: 'quarantine', remedyBy: 'x', detect() { return [] } }"
  )

  const result = run(['--check'], { script })
  assert.equal(result.status, 1)
  assert.match(result.stderr, /unprovable-residue: evidence none proves nothing/)
})

test('--check fails on a residue that claims any remedy other than a quarantine', (t) => {
  const script = pluginCopyWithTransition(
    t,
    "{ id: 'deleting-residue', species: 'residue', since: '0.20.0', decision: 'none', " +
      "subject: { path: '.claude/server/whatever.js' }, describe: 'x', " +
      "evidence: [{ type: 'pattern', source: 'x', flags: '' }], " +
      "remedy: 'delete', remedyBy: 'x', detect() { return [] } }"
  )

  const result = run(['--check'], { script })
  assert.equal(result.status, 1)
  assert.match(result.stderr, /deleting-residue: a residue is remedied by quarantine and by nothing else \(D55\)/)
})

test('--check refuses a remedy outside the declared vocabulary', (t) => {
  // --plan prints this word ahead of the sentence explaining it and a consumer groups on it, so
  // a fifth name has to fail at declaration time rather than reach a user's report.
  const script = pluginCopyWithTransition(
    t,
    "{ id: 'invented-remedy', species: 'gap', since: '0.20.0', decision: 'none', " +
      "subject: { entry: 'config', key: 'x' }, describe: 'x', " +
      "remedy: 'ask-somebody', remedyBy: 'x', detect() { return [] } }"
  )

  const result = run(['--check'], { script })
  assert.equal(result.status, 1)
  assert.match(result.stderr, /invented-remedy: unknown remedy "ask-somebody"/)
})

test('--check refuses evidence on anything that is not a residue', (t) => {
  const script = pluginCopyWithTransition(
    t,
    "{ id: 'value-with-evidence', species: 'value', since: '0.20.0', decision: 'none', " +
      "subject: { entry: 'config', key: 'x' }, describe: 'x', " +
      "evidence: [{ type: 'pattern', source: 'x', flags: '' }], " +
      "remedy: 'rewrite', remedyBy: 'x', detect() { return [] } }"
  )

  const result = run(['--check'], { script })
  assert.equal(result.status, 1)
  assert.match(result.stderr, /value-with-evidence: only a residue carries evidence/)
})

// ---------------------------------------------------------------------------
// --plan
// ---------------------------------------------------------------------------

// A project onboarded before every transition, carrying what each of them is about: the two
// retired artifacts, the two wrong values, the missing snapshot block and a run record from
// before the run block.
function legacyProject() {
  const repo = onboardedProject({
    runBlock: false,
    config: {
      onboard: { completedAt: '2026-08-06T10:00:00Z', pluginVersion: BEFORE_EVERYTHING },
      mcp: ['codebase-memory'],
      specialists: [{ name: 'typescript-pro', source: 'sub-agents.directory' }],
    },
    specialistTools: 'Read, Write, Edit, Bash',
    launchEntry: { program: '.claude/server/dashboard-server.js', args: ['.knowledge/dashboard.html'] },
  })
  const config = JSON.parse(fs.readFileSync(path.join(repo, '.claude', 'major-tom.json'), 'utf8'))
  delete config.snapshot
  write(repo, '.claude/major-tom.json', JSON.stringify(config, null, 2) + '\n')

  // The real bytes, not a stand-in: from D55 on, what these two files contain decides
  // whether anything is allowed to move them, so a fixture that only had the right path
  // would exercise the opposite branch from the one a real repository takes.
  write(repo, KNOWLEDGE_ROOT + '/dashboard.html', retiredDashboardArtifact())
  write(repo, '.claude/server/dashboard-server.js', RETIRED_DASHBOARD_SERVER)
  return repo
}

test('--plan reports a residue transition', (t) => {
  const repo = legacyProject()
  t.after(() => remove(repo))

  const result = run(['--plan', repo])
  assert.equal(result.status, 0, result.all)
  assert.match(result.stdout, /APPLIES {2}residue {2}dashboard-artifact/)
  assert.match(result.stdout, /APPLIES {2}residue {2}server-copy/)
  assert.match(result.stdout, /found: \.knowledge\/dashboard\.html/)
  assert.match(result.stdout, /found: \.claude\/server\/dashboard-server\.js/)
})

test('--plan reports a value transition with the value it derives', (t) => {
  const repo = legacyProject()
  t.after(() => remove(repo))

  const result = run(['--plan', repo])
  assert.match(result.stdout, /APPLIES {2}value {2}mcp-server-name/)
  assert.match(result.stdout, /mcp lists codebase-memory, expected codebase-memory-mcp/)
  assert.match(result.stdout, /APPLIES {2}value {2}specialist-tools/)
  assert.match(result.stdout, /Read, Glob, Grep, mcp__codebase-memory__\*/)
  assert.match(result.stdout, /APPLIES {2}value {2}launch-entry/)
  assert.match(result.stdout, /program is "\.claude\/server\/dashboard-server\.js"/)
})

test('--plan reports a gap transition and says it needs the interview', (t) => {
  const repo = legacyProject()
  t.after(() => remove(repo))

  const result = run(['--plan', repo])
  assert.match(result.stdout, /APPLIES {2}gap {2}snapshot-block/)
  assert.match(result.stdout, /config carries no snapshot block/)
  assert.match(result.stdout, /remedy: interview;/)
})

test('--plan reports the missing run block as a gap the next run closes', (t) => {
  const repo = legacyProject()
  t.after(() => remove(repo))

  const result = run(['--plan', repo])
  assert.equal(result.status, 0, result.all)
  assert.match(result.stdout, /APPLIES {2}gap {2}run-block/)
  assert.match(result.stdout, /none of them carrying a run block/)
  assert.match(result.stdout, /remedy: next-run; re-run \/major-tom:onboard/)
})

test('--plan never asks anyone to repair a record written before the run block', (t) => {
  // The report a user of an older repository reads. An older record is a complete record, so
  // the plan may say what the dashboard lacks and what supplies it, and may not say that
  // anything on disk is broken or has to be rewritten.
  const repo = legacyProject()
  t.after(() => remove(repo))

  const result = run(['--plan', repo])
  assert.match(result.stdout, /A record written before it is a complete record all the same/)
  assert.match(result.stdout, /--verify calls it ok/)
  assert.match(result.stdout, /Nothing repairs a record already written and nothing should/)
  assert.match(result.stdout, /Every record already on disk stays exactly as it is/)
})

test('--plan says nothing about the run block once any record carries one', (t) => {
  // A pre-block record beside a current one is complete history rather than a defect: the
  // dashboard reads the newest record that has a block, so nothing is left for anyone to do.
  const repo = onboardedProject({
    runBlock: false,
    config: { onboard: { completedAt: '2026-08-06T10:00:00Z', pluginVersion: BEFORE_EVERYTHING } },
  })
  t.after(() => remove(repo))

  const second = 'onboard-2026-09-10T12-00-00-000Z.md'
  write(repo, KNOWLEDGE_ROOT + '/runs/' + second, runRecord({ runBlock: true, name: second }))

  const result = run(['--plan', repo])
  assert.equal(result.status, 0, result.all)
  assert.equal(lineFor(result.stdout, 'APPLIES', 'run-block').length, 0, result.all)
  assert.match(result.stdout, /CLEAR {4}gap {2}run-block/)
})

test('--plan reports the run-block gap only where a record exists to lack it', (t) => {
  // With no record at all the artifact is MISSING, which --verify names and a re-onboard
  // restores. Reporting a gap for the same fact would offer a second, different remedy for it.
  const repo = onboardedProject({ runBlock: false })
  t.after(() => remove(repo))

  fs.rmSync(path.join(repo, KNOWLEDGE_ROOT, 'runs', RUN_RECORD_NAME))

  const plan = run(['--plan', repo])
  assert.equal(plan.status, 0, plan.all)
  assert.equal(lineFor(plan.stdout, 'APPLIES', 'run-block').length, 0, plan.all)

  const verify = run(['--verify', repo])
  assert.equal(statusOf(verify.stdout, KNOWLEDGE_ROOT + '/runs/onboard-*.md'), 'MISSING', verify.all)
})

test('--plan names the three species and never any other', (t) => {
  const repo = legacyProject()
  t.after(() => remove(repo))

  const result = run(['--plan', repo])
  const species = new Set(
    result.stdout
      .split('\n')
      .map((line) => /^(?:APPLIES|CLEAR) {2}(\S+)/.exec(line))
      .filter(Boolean)
      .map((m) => m[1])
  )
  assert.deepEqual([...species].sort(), ['gap', 'residue', 'value'])
})

// This test replaced one that asserted the opposite text, "remedy: delete; undecided
// (OQ-16)". OQ-16 is closed by D55 and it closed against deletion, so the old assertion now
// describes a behaviour the plugin is not allowed to have.
test('--plan says the remedy is a quarantine, and never a deletion', (t) => {
  const repo = legacyProject()
  t.after(() => remove(repo))

  const result = run(['--plan', repo])
  assert.equal(result.status, 0, result.all)
  assert.equal(lineFor(result.stdout, 'APPLIES', 'dashboard-artifact').length, 1, result.all)
  assert.match(result.stdout, /remedy: quarantine; node migration\.js --quarantine/)
  assert.match(result.stdout, /never deletes it \(D55\)/)
  assert.equal(result.stdout.indexOf('OQ-16'), -1, 'OQ-16 is closed and must not be quoted as open')
  assert.equal(result.stdout.indexOf('remedy: delete'), -1, 'nothing here deletes')
})

test('--plan says a residue whose evidence holds is one --quarantine will move', (t) => {
  const repo = legacyProject()
  t.after(() => remove(repo))

  const result = run(['--plan', repo])
  assert.match(result.stdout, /found: \.knowledge\/dashboard\.html {2}-- the evidence holds, so --quarantine will move this one/)
  assert.match(
    result.stdout,
    /found: \.claude\/server\/dashboard-server\.js {2}-- the evidence holds, so --quarantine will move this one/
  )
})

test('--plan says so when a residue path holds a file the map cannot prove is ours', (t) => {
  // Somebody else's dashboard.html, at the path the retired artifact used. --plan must not
  // imply a remedy that is never going to reach this file.
  const repo = onboardedProject()
  t.after(() => remove(repo))
  write(repo, KNOWLEDGE_ROOT + '/dashboard.html', '<!doctype html>\n<title>My own notes</title>\n')

  const result = run(['--plan', repo])
  assert.equal(result.status, 0, result.all)
  assert.match(result.stdout, /APPLIES {2}residue {2}dashboard-artifact/)
  assert.match(result.stdout, /found: \.knowledge\/dashboard\.html {2}-- the evidence does NOT hold/)
  assert.match(result.stdout, /so nothing will touch it/)
})

test('--plan reports nothing applicable for a current project', (t) => {
  const repo = onboardedProject()
  t.after(() => remove(repo))

  const result = run(['--plan', repo])
  assert.equal(result.status, 0, result.all)
  assert.match(result.stdout, /plan: 0 applies, 0 clear, \d+ not applicable/)
})

test('--plan separates what applies by version from what this repository actually carries', (t) => {
  // Onboarded before every transition, but carrying none of them: the version says the
  // transitions could apply and the repository says they do not, and a report that only
  // compared versions would send this user to fix six things that are not there.
  const repo = onboardedProject({
    config: { onboard: { completedAt: '2026-08-06T10:00:00Z', pluginVersion: BEFORE_EVERYTHING } },
  })
  t.after(() => remove(repo))

  const result = run(['--plan', repo])
  assert.equal(result.status, 0, result.all)
  assert.match(result.stdout, /plan: 0 applies, 7 clear, 0 not applicable/)
  assert.match(result.stdout, /CLEAR {4}residue {2}dashboard-artifact/)
  assert.match(result.stdout, /CLEAR {4}gap {2}run-block/)
})

test('--plan reports a residue even when the recorded version would not predict it', (t) => {
  // A config can be hand-edited or re-onboarded without the residue being cleared, so
  // detection is over the repository and the version only decides what to look for.
  const repo = onboardedProject()
  t.after(() => remove(repo))
  write(repo, '.claude/server/dashboard-server.js', '// left behind\n')

  const result = run(['--plan', repo])
  assert.match(result.stdout, /APPLIES {2}residue {2}server-copy/)
})

test('--plan writes nothing, moves nothing and deletes nothing', (t) => {
  const repo = legacyProject()
  t.after(() => remove(repo))

  const before = treeDigest(repo)
  const beforeListing = listTree(repo)

  const result = run(['--plan', repo])
  assert.equal(result.status, 0, result.all)

  const after = treeDigest(repo)
  assert.deepEqual(listTree(repo), beforeListing, 'the set of paths must be identical before and after')
  assert.equal(after, before, 'the whole tree must hash identically before and after')
  assert.match(result.stdout, /Nothing was written, moved or deleted/)
})

test('--plan refuses a directory that is not an onboarded project', (t) => {
  const repo = tempDir('major-tom-map-bare-')
  t.after(() => remove(repo))

  const result = run(['--plan', repo])
  assert.equal(result.status, 1)
  assert.match(result.stderr, /nothing to migrate/)
})

function listTree(root) {
  const out = []
  const walk = (dir, prefix) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => (a.name < b.name ? -1 : 1))) {
      const rel = prefix ? prefix + '/' + entry.name : entry.name
      out.push((entry.isDirectory() ? 'D ' : 'F ') + rel)
      if (entry.isDirectory()) walk(path.join(dir, entry.name), rel)
    }
  }
  walk(root, '')
  return out
}

// ---------------------------------------------------------------------------
// --quarantine
//
// The only mode that writes, so this is the only section where an assertion that the tree
// changed is a pass. Every test here checks both halves of the promise: what moved, and that
// nothing else did.
// ---------------------------------------------------------------------------

test('--quarantine renames a proven residue in place and leaves nothing at the old path', (t) => {
  const repo = legacyProject()
  t.after(() => remove(repo))

  const originalHtml = fs.readFileSync(path.join(repo, KNOWLEDGE_ROOT, 'dashboard.html'))
  const originalServer = fs.readFileSync(path.join(repo, '.claude', 'server', 'dashboard-server.js'))

  const result = run(['--quarantine', repo])
  assert.equal(result.status, 0, result.all)

  for (const [rel, original] of [
    [KNOWLEDGE_ROOT + '/dashboard.html', originalHtml],
    ['.claude/server/dashboard-server.js', originalServer],
  ]) {
    assert.equal(fs.existsSync(path.join(repo, rel)), false, rel + ' must be gone from its old path')
    const moved = path.join(repo, rel + RETIRED_SUFFIX)
    assert.equal(fs.existsSync(moved), true, rel + RETIRED_SUFFIX + ' must exist')
    assert.ok(fs.readFileSync(moved).equals(original), 'a rename keeps the bytes; nothing is rewritten on the way')
    assert.equal(lineFor(result.stdout, 'QUARANTINED', rel).length, 1, result.all)
  }
  assert.match(result.stdout, /QUARANTINED {3}\.knowledge\/dashboard\.html -> \.knowledge\/dashboard\.html\.retired/)
  assert.match(result.stdout, /quarantine: 2 quarantined, 0 skipped, 0 failed/)
})

test('--quarantine changes exactly the paths it printed and nothing else', (t) => {
  const repo = legacyProject()
  t.after(() => remove(repo))

  const before = listTree(repo)
  const result = run(['--quarantine', repo])
  assert.equal(result.status, 0, result.all)
  const after = listTree(repo)

  const removed = before.filter((p) => after.indexOf(p) === -1).sort()
  const added = after.filter((p) => before.indexOf(p) === -1).sort()

  const printed = result.stdout
    .split('\n')
    .filter((line) => line.startsWith('QUARANTINED '))
    .map((line) => line.replace(/^QUARANTINED\s+/, '').split(' -> '))

  assert.equal(printed.length, 2, result.all)
  assert.deepEqual(removed, printed.map(([from]) => 'F ' + from).sort(), 'exactly the printed sources disappeared')
  assert.deepEqual(added, printed.map(([, to]) => 'F ' + to).sort(), 'exactly the printed destinations appeared')

  // And every path that neither moved nor arrived still holds the same bytes: a rename is
  // the whole change, not the part of it that happened to be reported.
  const untouched = before.filter((p) => removed.indexOf(p) === -1 && p.startsWith('F '))
  for (const marker of untouched) {
    const rel = marker.slice(2)
    assert.equal(fs.existsSync(path.join(repo, rel)), true, rel + ' must survive untouched')
  }
})

test('--quarantine never touches a residue path whose evidence does not hold', (t) => {
  const repo = onboardedProject()
  t.after(() => remove(repo))

  // Same path, somebody else's file. A path match is not proof of authorship, and this is
  // the case D55 point 3 exists for.
  const stranger = '<!doctype html>\n<title>My own notes</title>\n<p>Mine.</p>\n'
  write(repo, KNOWLEDGE_ROOT + '/dashboard.html', stranger)
  const before = treeDigest(repo)

  const result = run(['--quarantine', repo])
  assert.equal(result.status, 0, 'a refusal to touch a file is a report, not a failure')
  assert.equal(treeDigest(repo), before, 'nothing at all may change')
  assert.equal(fs.readFileSync(path.join(repo, KNOWLEDGE_ROOT, 'dashboard.html'), 'utf8'), stranger)
  assert.equal(fs.existsSync(path.join(repo, KNOWLEDGE_ROOT, 'dashboard.html' + RETIRED_SUFFIX)), false)
  assert.equal(lineFor(result.stdout, 'SKIPPED', KNOWLEDGE_ROOT + '/dashboard.html').length, 1, result.all)
  assert.match(result.stdout, /the evidence that this is ours does not hold/)
  assert.match(result.stdout, /major-tom-data/, 'the report has to say which predicate failed')
  assert.match(result.stdout, /quarantine: 0 quarantined, 1 skipped, 0 failed/)
})

test('--quarantine refuses a residue that carries only part of the evidence', (t) => {
  // The dashboard this plugin serves today: the same title, no data island, and never
  // written into a target at all. One predicate holds and one does not, and all of them have
  // to hold before anything moves.
  const repo = onboardedProject()
  t.after(() => remove(repo))

  fs.copyFileSync(path.join(PLUGIN_ROOT, 'app', 'dashboard.html'), path.join(repo, KNOWLEDGE_ROOT, 'dashboard.html'))
  const before = treeDigest(repo)

  const result = run(['--quarantine', repo])
  assert.equal(result.status, 0, result.all)
  assert.equal(treeDigest(repo), before, 'nothing at all may change')
  assert.equal(lineFor(result.stdout, 'SKIPPED', KNOWLEDGE_ROOT + '/dashboard.html').length, 1, result.all)
  assert.match(result.stdout, /major-tom-data/)
})

test('--quarantine never overwrites a destination that already exists', (t) => {
  const repo = onboardedProject()
  t.after(() => remove(repo))

  write(repo, '.claude/server/dashboard-server.js', RETIRED_DASHBOARD_SERVER)
  // Whatever is already sitting at the destination is the user's, whether they put it there
  // or an earlier run did. Overwriting it would destroy it, which is the act D55 forbids
  // under any name.
  const occupant = '// the user kept notes in this file\n'
  write(repo, '.claude/server/dashboard-server.js' + RETIRED_SUFFIX, occupant)

  const before = treeDigest(repo)
  const result = run(['--quarantine', repo])

  assert.equal(result.status, 0, 'a refusal to overwrite is a report, not a failure')
  assert.equal(treeDigest(repo), before, 'neither the residue nor the occupant may change')
  // Stated on its own rather than left to the digest, because this is the property the whole
  // decision rests on: not merely that no rename happened, but that the bytes already sitting
  // at the destination are the bytes still sitting there afterwards.
  assert.equal(
    fs.readFileSync(path.join(repo, '.claude', 'server', 'dashboard-server.js' + RETIRED_SUFFIX), 'utf8'),
    occupant,
    'the file already at the destination must survive byte for byte'
  )
  assert.equal(
    fs.readFileSync(path.join(repo, '.claude', 'server', 'dashboard-server.js'), 'utf8'),
    RETIRED_DASHBOARD_SERVER,
    'and the residue must still be there, under its original name, byte for byte'
  )
  assert.equal(lineFor(result.stdout, 'SKIPPED', '.claude/server/dashboard-server.js').length, 1, result.all)
  assert.match(result.stdout, /already exists; nothing is ever overwritten/)
  assert.match(result.stdout, /quarantine: 0 quarantined, 1 skipped, 0 failed/)
})

test('--quarantine reports a real I/O failure, exits non-zero, and leaves the residue intact', (t) => {
  // The only path in this feature that can abort an onboard, so it is the one that most needs
  // a test rather than a reading. The failure is produced by the filesystem, not by a stub:
  // a directory the process may read and traverse but not write cannot be renamed within, so
  // renameSync raises EACCES exactly as it would on a read-only checkout or a locked volume.
  //
  // Root ignores those permission bits. Under root the rename would succeed, this test would
  // pass, and it would have proved nothing at all, which is worse than not having it, so it
  // says why it did not run rather than reporting a pass it did not earn.
  if (typeof process.getuid === 'function' && process.getuid() === 0) {
    t.skip('running as root: the directory permission bits this test depends on are not enforced for root, so the rename would succeed and the test would pass without exercising the failure path')
    return
  }

  const repo = onboardedProject()
  const dir = path.join(repo, '.claude', 'server')
  // Restoring the mode is registered before the directory is ever made unwritable, and it runs
  // whether the test passes or throws. A failing assertion must not leave an undeletable
  // directory behind in os.tmpdir(): remove() cannot unlink the files inside a 0555 directory,
  // so the chmod has to come first here and it has to be unconditional.
  t.after(() => {
    try {
      fs.chmodSync(dir, 0o755)
    } catch (err) {
      // Already restored, or the directory is gone. Either way there is nothing left to fix,
      // and throwing from a cleanup would hide whatever the test itself reported.
    }
    remove(repo)
  })

  const residue = path.join(dir, 'dashboard-server.js')
  write(repo, '.claude/server/dashboard-server.js', RETIRED_DASHBOARD_SERVER)
  fs.chmodSync(dir, 0o555)

  const result = run(['--quarantine', repo])

  const failedLines = result.stderr.split('\n').filter((line) => line.startsWith('FAILED '))
  assert.equal(failedLines.length, 1, 'one failure, one line\n' + result.all)
  assert.match(failedLines[0], /\.claude\/server\/dashboard-server\.js/, 'the line must name the path it could not move')
  assert.match(failedLines[0], /EACCES/, 'and must carry what the filesystem actually said, not a paraphrase')

  assert.notEqual(result.status, 0, 'a mode that did not do what it said it did must fail')
  assert.match(result.stdout, /quarantine: 0 quarantined, 0 skipped, 1 failed/, result.all)

  // The point of the whole design: when the move cannot happen, the file is exactly as it was.
  assert.equal(fs.existsSync(residue), true, 'the residue must still be there')
  assert.equal(fs.readFileSync(residue, 'utf8'), RETIRED_DASHBOARD_SERVER, 'under its original name, byte for byte')
  assert.equal(fs.existsSync(residue + RETIRED_SUFFIX), false, 'and nothing may have been created at the destination')
})

test('--quarantine on a repository with no residue is a no-op that exits 0', (t) => {
  const repo = onboardedProject()
  t.after(() => remove(repo))

  const before = treeDigest(repo)
  const beforeListing = listTree(repo)

  const result = run(['--quarantine', repo])
  assert.equal(result.status, 0, result.all)
  assert.deepEqual(listTree(repo), beforeListing, 'the set of paths must be identical before and after')
  assert.equal(treeDigest(repo), before, 'the whole tree must hash identically before and after')
  assert.match(result.stdout, /quarantine: 0 quarantined, 0 skipped, 0 failed/)
})

test('--quarantine never re-reads, re-moves or cleans up a .retired file it already made', (t) => {
  const repo = legacyProject()
  t.after(() => remove(repo))

  assert.equal(run(['--quarantine', repo]).status, 0)
  const after = treeDigest(repo)

  const second = run(['--quarantine', repo])
  assert.equal(second.status, 0, second.all)
  assert.equal(treeDigest(repo), after, 'a .retired file is never re-read, re-moved or cleaned up (D55 point 4)')
  assert.match(second.stdout, /quarantine: 0 quarantined, 0 skipped, 0 failed/)
})

test('--quarantine refuses a directory that is not an onboarded project', (t) => {
  const repo = tempDir('major-tom-map-bare-')
  t.after(() => remove(repo))

  const result = run(['--quarantine', repo])
  assert.equal(result.status, 1)
  assert.match(result.stderr, /not an onboarded project/)
})

test('--verify accepts a legacy project once its residue has been quarantined', (t) => {
  // The end-to-end shape of the remedy: what was two RETIRED problems is two informative
  // quarantined lines, and neither of them is UNEXPECTED.
  const repo = legacyProject()
  t.after(() => remove(repo))

  const before = run(['--verify', repo])
  assert.match(before.stdout, /2 retired, 0 quarantined/)

  assert.equal(run(['--quarantine', repo]).status, 0)

  const after = run(['--verify', repo])
  assert.match(after.stdout, /0 unexpected, 0 retired, 2 quarantined/, after.all)
  assert.equal(lineFor(after.stdout, 'UNEXPECTED', RETIRED_SUFFIX).length, 0, after.all)
})

// ---------------------------------------------------------------------------
// CLI surface
// ---------------------------------------------------------------------------

test('an unknown mode fails with the usage line rather than doing something', () => {
  const result = run(['--migrate', '.'])
  assert.equal(result.status, 1)
  assert.match(result.stderr, /usage: node migration\.js --verify/)
})

test('no mode at all fails the same way', () => {
  const result = run([])
  assert.equal(result.status, 1)
  assert.match(result.stderr, /usage: node migration\.js --verify/)
})
