#!/usr/bin/env node
// The Major Tom dashboard server (D31, as rebuilt by D43 points 1, 2, 5 and 8 and by D44
// points 5 and 7). Node's own http, zero dependencies.
//
// Usage: node server.js <repo-root> [port]
//
// The file lives in the plugin and is never copied into a target repository (D44 point 2):
// the /major-tom:dashboard command and the launcher written into .claude/server/ both run
// this file from the plugin root and pass it the repository it should read.
//
// It serves two things and nothing else: the built dashboard.html sitting beside it, and the
// read-only JSON that page fetches. 127.0.0.1 only, GET only, 405 for any other method.
//
//   GET /                            the built page
//   GET /api/snapshot                the snapshot for the served repository, computed here
//   GET /api/knowledge/body?id=<id>  the body of the one concept that id addresses
//   anything else                    404
//
// GET only is meant literally, and HEAD is not exempt: a HEAD request is answered 405 like
// any other non-GET method. That is a deviation from the HTTP norm, under which a server
// supporting GET on a target supports HEAD on it too, and it is stated here so it is a choice
// and not an accident. The reason it stays: this is a same-origin API for one page, nothing
// in the client issues a HEAD, and answering one would mean a second response path whose only
// job is to compute a full body and then discard it. A 405 with the JSON error shape tells a
// caller exactly as much and costs nothing to be sure of.
//
// Every response that is not a success carries the same JSON body, {"error": "<message>"},
// produced by the one sendError below and never assembled at a call site. A client may
// therefore parse any non-2xx response as JSON without first inspecting its status or its
// content type. Only GET / on success answers something other than JSON, the page itself.
//
// The three properties this file exists to hold:
//
// 1. No path parameter is ever taken from a request, and no path is held here at all (D43
//    point 8). Every route above is a literal string compared against the request's pathname,
//    and the only file this process opens on behalf of a request is the page beside it, at a
//    path built from __dirname. No request string ever reaches the filesystem, so the server
//    cannot be turned into an arbitrary file reader on the machine of whoever runs it. The
//    directory-serving mode the old static server carried is gone for the same reason, and
//    with it its path-traversal guard, its realpath root and its MIME table: D44 point 7 kept
//    the bundler precisely so the server serves one known file instead of a directory tree
//    with path resolution, and keeping that mode would hand back exactly the surface the
//    decision bought.
//
//    The body route holds the property structurally rather than by care: the id it reads from
//    the query string is passed straight to snapshot.js, which resolves it against the concept
//    list it recomputes from disk and answers with a body or with null. This file never learns
//    which file was read, never builds a path and has nothing to sanitize, so an id that looks
//    like a path is simply an id that matches no concept.
//
// 2. No cache and no separate recompute verb. Every GET /api/snapshot recomputes from disk,
//    and the page's refresh control is the same request issued again (D43 point 5). This is
//    the same reasoning that rejected fs.watch: state the server does not keep is state that
//    cannot go stale. The page is likewise read from disk on every request, so a rebuild
//    shows up on a browser refresh.
//
// 3. A bad repository is a response, not a crash. buildSnapshot throws a SnapshotError on
//    every fail-closed condition (no .claude/major-tom.json, a config that does not parse, a
//    missing persistence root), which is answered with a 500 carrying the message, so the
//    page can tell the user the repository is not onboarded instead of showing a blank view.
//    Any other exception is a defect: also a 500, but with the stack written to stderr and
//    never to the client. No request can end this process.
//
// Fail closed at startup, by contrast, is an exit: a missing or non-directory repo root, a
// port that is not a port, a missing dashboard.html and a port already in use are all
// conditions no request can fix, so they are reported and the process leaves.

'use strict'

const http = require('http')
const fs = require('fs')
const path = require('path')

const { buildSnapshot, readConceptBody, SnapshotError } = require('./snapshot.js')

// The one file a request can cause this process to open, resolved from this file's own
// location and never from anything a client sent. Generated by scripts/build-dashboard.js
// from ./dashboard/ (D34, confirmed by D44 point 7) and shipped beside this server.
const PAGE = path.join(__dirname, 'dashboard.html')

const USAGE = 'usage: node server.js <repo-root> [port]'

// The one address this process binds. It is a literal here and never comes from a caller:
// the dashboard is a local page over local data and has no business accepting a connection
// from the network. It is also what the startup line announces, read back from the socket.
const HOST = '127.0.0.1'

const DEFAULT_PORT = 4242

// Every startup refusal goes through here, so the message register and the exit code are the
// same for all of them and no check can invent its own. It never returns.
function refuse(message) {
  console.error(`server.js: ${message}`)
  process.exit(1)
}

// A port supplied by a caller, in the same fail-closed register as every other startup check:
// a value that is not a port number is a refusal with a message and a non-zero exit, never a
// silent fallback to some other port. The old Number(...) || Number(...) || 4242 was exactly
// that silent fallback, and it treated "banana" (NaN, falsy) and 0 (falsy) as "not supplied".
//
// Digits only, so a sign, a decimal point, a hex literal, whitespace inside the value or a
// trailing unit are all refused instead of coerced: Number('') is 0 and Number(' 80 ') is 80,
// and neither of those readings is something a caller asked for.
//
// Port 0 is honoured, and means what it means to bind(2): let the kernel choose a free port.
// Refusing it was the other defensible reading and it was not taken, because the launcher
// (D32) forwards whatever Claude Desktop's autoPort mechanism supplies straight into this
// argument, and "any free port" is precisely what that mechanism exists to express; a refusal
// would turn a legitimate request into a startup failure. Honouring it is only safe because
// the startup line is read back from the bound socket rather than from this value, so a caller
// that asked for 0 is told the port it actually got. An out-of-range or non-numeric value
// stays an error: those name a port that cannot exist, while 0 names one the kernel picks.
function parsePort(value, source) {
  const text = String(value)
  if (!/^[0-9]+$/.test(text) || Number(text) > 65535) {
    refuse(`${source} is not a port number: ${JSON.stringify(text)}; give a whole number from 0 to 65535, where 0 asks the kernel for a free port`)
  }
  return Number(text)
}

const repoRootArg = process.argv[2]

if (!repoRootArg) {
  console.error(USAGE)
  process.exit(1)
}

const repoRoot = path.resolve(repoRootArg)
let repoStat = null
try {
  repoStat = fs.statSync(repoRoot)
} catch (e) {
  refuse(`repo root ${repoRoot} does not exist (${e.message})`)
}
if (!repoStat.isDirectory()) {
  refuse(`repo root ${repoRoot} is not a directory`)
}

// Resolution order unchanged: explicit argument, else the PORT env var (what the Claude
// Desktop launch.json autoPort mechanism passes when it picks a free port, D32), else 4242.
// What changed is that each source is validated when it is present instead of being coerced
// and dropped when the coercion fails.
//
// An argument is "present" whenever argv holds one, empty string included: a positional that
// was typed cannot mean "use the default", so `server.js <repo> ""` is a refusal. An unset
// PORT and an empty PORT are the same absence, because exporting a variable to the empty
// string is the ordinary shell way of saying nothing, and a process that inherits one has not
// been asked for a port at all; any other PORT value is validated exactly like the argument.
const portArg = process.argv[3]
const portEnv = process.env.PORT
let port
if (portArg !== undefined) {
  port = parsePort(portArg, 'the port argument')
} else if (portEnv !== undefined && portEnv.trim() !== '') {
  port = parsePort(portEnv, 'the PORT environment variable')
} else {
  port = DEFAULT_PORT
}

// Checked once, here, rather than on the first request: a server that cannot serve its own
// page is broken before anyone asks it for anything, and the repair is a build, not a retry.
if (!fs.existsSync(PAGE)) {
  refuse(`${PAGE} is missing; run node scripts/build-dashboard.js to build it`)
}

function sendJson(res, status, value) {
  res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' })
  res.end(`${JSON.stringify(value, null, 2)}\n`)
}

// Every non-success response in this file, without exception: the two 404s, the 405 and both
// 500s. It exists as one function rather than as a shape repeated at five call sites so that
// the contract stated in the header, that any non-2xx response parses as JSON and carries an
// error string, is a property of there being one producer and not of five call sites agreeing.
// The 404 for an unknown route and the 405 for a non-GET method used to be text/plain and are
// not any more: a client written against this API reads a status and a body, and a body it
// cannot parse on exactly the two commonest failures is a trap.
function sendError(res, status, message) {
  sendJson(res, status, { error: message })
}

// Read on every request, and read synchronously so a read failure lands in the one handler
// below as a 500 instead of arriving later on a stream whose headers are already out.
function sendPage(res) {
  const html = fs.readFileSync(PAGE)
  res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' })
  res.end(html)
}

// The request target up to the query, compared literally and never resolved. WHATWG URL is
// deliberately not used for this: parsing against a base accepts "//host/api/snapshot" as the
// snapshot route (the leading "//" reads as protocol-relative) and collapses ".." segments
// before the comparison, so it would route request targets this server does not declare.
// A literal match declares exactly the targets below and answers 404 to everything else.
function routeOf(requestTarget) {
  const q = requestTarget.indexOf('?')
  return q === -1 ? requestTarget : requestTarget.slice(0, q)
}

// The query string of the request target, parsed on its own. URLSearchParams parses a query
// and only a query, so nothing here resolves a path, which is the same reason routeOf compares
// literally: the WHATWG URL constructor would have to be given a base, and parsing against a
// base rewrites the target before this file ever sees it.
function queryOf(requestTarget) {
  return new URLSearchParams(requestTarget.split('?')[1] || '')
}

// Routing by literal string comparison. Nothing taken from a request is ever joined to a
// filesystem path, here or anywhere below (D43 point 8).
function handle(req, res) {
  // HEAD included, deliberately and as the header states.
  if (req.method !== 'GET') {
    sendError(res, 405, 'method not allowed: this server answers GET and nothing else')
    return
  }

  const route = routeOf(req.url)

  if (route === '/') {
    sendPage(res)
    return
  }

  if (route === '/api/snapshot') {
    sendJson(res, 200, buildSnapshot({ repoRoot }))
    return
  }

  if (route === '/api/knowledge/body') {
    // get returns null when the parameter is absent, and readConceptBody answers a null, an
    // empty or an unminted id the same way it answers an id no concept carries: with null.
    // One 404 covers all of them, because from here they are the same fact, that no concept
    // is addressed. A fail-closed repository throws instead and is caught below as a 500,
    // and it throws whether or not the request carried an id: readConceptBody reads the
    // config before it judges the id, so one broken repository has one diagnosis here and
    // the query string cannot change it.
    const id = queryOf(req.url).get('id')
    const body = readConceptBody({ repoRoot, id })
    if (body === null) {
      sendError(res, 404, 'no knowledge file carries that id')
      return
    }
    sendJson(res, 200, { id, body })
    return
  }

  // The route is not named back to the caller. Nothing taken from a request is echoed into a
  // response here, for the same reason nothing taken from a request reaches the filesystem:
  // an error message is the one place where a reflected request string tends to creep in, and
  // this server has nothing to say about the target that the caller does not already know.
  sendError(res, 404, 'not found: this server serves /, /api/snapshot and /api/knowledge/body')
}

const server = http.createServer((req, res) => {
  try {
    handle(req, res)
  } catch (e) {
    // Headers already out means a handler failed mid-response; there is no status left to
    // send, so the connection is dropped rather than a second reply appended to the first.
    if (res.headersSent) {
      console.error(`server.js: failure after the response began for ${req.method} ${req.url}`)
      console.error(e && e.stack ? e.stack : e)
      res.destroy()
      return
    }
    if (e instanceof SnapshotError) {
      // A refused input, not a defect: the repository is not onboarded or its config is
      // broken. The message is the useful part and it goes to the client so the page can
      // name what is wrong.
      sendError(res, 500, e.message)
      return
    }
    // A defect. The stack is a fact about this code, not about the caller's repository, so
    // it goes to stderr and the client gets a bare acknowledgement.
    console.error(`server.js: unhandled error serving ${req.method} ${req.url}`)
    console.error(e && e.stack ? e.stack : e)
    sendError(res, 500, 'internal server error; see the server log')
  }
})

server.on('error', (err) => {
  if (err.code === 'EADDRINUSE') {
    refuse(`port ${port} is already in use (another dashboard server?); pass a different port`)
  }
  refuse(err.message)
})

// The address announced is the address bound, read back from the socket and not rebuilt from
// what was asked for. It used to print localhost while binding 127.0.0.1, which is wrong on
// any host where localhost resolves to ::1 first: the printed URL is the string a user copies
// into a browser, and nothing is listening on ::1. Reading the port back is also what makes
// port 0 usable, since the caller learns which port the kernel chose.
server.listen(port, HOST, () => {
  const bound = server.address()
  console.log(`major-tom dashboard on http://${bound.address}:${bound.port} (reading ${repoRoot})`)
})
